chat:
  distance: 50
  shout:
    prefix: "ยงa[Shout] "
  ask:
    prefix: "ยง9[Question] "

economy:
  symbol: "$"
  name:
    singular: "Dollar"
    plural: "Dollars"
  startMoney: 100
  distance: 50
  sellFee: 0.2