core:
  prefix: "§aRedFix » "

commandspy:
  prefix: "§cCommandSpy » "
  enable: "§7CommandSpy wurde §eaktiviert"
  disable: "§7CommandSpy wurde §edeaktiviert"

chat:
  #-1 For disable
  distance: -1
  shout:
    prefix: "§a[Shout] "
  ask:
    prefix: "§9[Question] "

economy:
  symbol: "$"
  name:
    singular: "Dollar"
    plural: "Dollars"
  startMoney: 100
  distance: 50
  sellFee: 0.2