core:
  prefix: "§aRedFix » "

commandspy:
  prefix: "§cCommandSpy » "
  enable: "§7CommandSpy wurde §eaktiviert"
  disable: "§7CommandSpy wurde §edeaktiviert"

chat:
  #-1 For disable
  distance: -1
  shout:
    enabled: false
    prefix: "§a[Shout] "
    name: "Shout"
  ask:
    enabled: false
    prefix: "§9[Question] "
    name: "Question"

economy:
  enabled: true
  symbol: "$"
  name:
    singular: "Dollar"
    plural: "Dollars"
  startMoney: 100
  distance: 50
  sellFee: 0.2

commands:
  home:
    cooldown: 10
  warp:
    cooldown: 10

auto-unlock-recipes: false

mysql:
  enabled: true
  host: "localhost"
  port: 3306
  database: "Minecraft_Network"
  username: "mcnetwork"
  password: "l9wAS?3oO+1!B0wFjQ#&"
  prefix: "rf_"
  modules:
    economy: true

