core:
  prefix: "§aRedFix » "

commandspy:
  prefix: "§cCommandSpy » "
  enable: "§7CommandSpy wurde §eaktiviert"
  disable: "§7CommandSpy wurde §edeaktiviert"

chat:
  #-1 For disable
  distance: -1
  shout:
    prefix: "§a[Shout] "
    name: "Shout"
  ask:
    prefix: "§9[Question] "
    name: "Question"

economy:
  enabled: true
  symbol: "$"
  name:
    singular: "Dollar"
    plural: "Dollars"
  startMoney: 100
  distance: 50
  sellFee: 0.2

commands:
  home:
    cooldown: 10
  warp:
    cooldown: 10

auto-unlock-recipes: false