core:
  prefix: "§aRedFix » "

commandspy:
  prefix: "§cCommandSpy » "
  enable: "§7CommandSpy wurde §eaktiviert"
  disable: "§7CommandSpy wurde §edeaktiviert"

afk:
  enabled: false

chat:
  enabled: false
  #-1 For disable
  distance: -1
  shout:
    enabled: false
    prefix: "§a[Shout] "
    name: "Shout"
  ask:
    enabled: false
    prefix: "§9[Question] "
    name: "Question"

economy:
  enabled: true
  symbol: "$"
  name:
    singular: "Dollar"
    plural: "Dollars"
  startMoney: 100
  distance: 50
  sellFee: 0.2

commands:
  home:
    cooldown: 10
  warp:
    cooldown: 10

auto-unlock-recipes: false

mysql:
  enabled: false
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""
  prefix: "rf_"
  modules:
    economy: false
    nick: false

color:
  anvil: false
  sign: false
  book: false
